"""
Agent Intelligence Domain Models

Database models for agent capability profiles.
"""
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import Column, String, Text, ForeignKey, Float, DateTime, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSONB
from sqlalchemy.orm import relationship

from core.database.base import Base


class AgentCapabilityProfile(Base):
    """
    Agent capability profile - structured intelligence about an agent.
    
    Generated by analyzing agent metadata, tools, and configuration.
    """
    __tablename__ = "agent_capability_profiles"

    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)
    agent_id = Column(PG_UUID(as_uuid=True), ForeignKey("agents.id", ondelete="CASCADE"), nullable=False)
    version_id = Column(PG_UUID(as_uuid=True), ForeignKey("agent_versions.id", ondelete="SET NULL"), nullable=True)
    
    # Core understanding
    primary_goal = Column(Text, nullable=True)
    secondary_goals = Column(JSONB, nullable=False, default=list)  # array of strings
    
    # Capabilities
    capabilities = Column(JSONB, nullable=False, default=list)  # array of capability objects
    domains = Column(JSONB, nullable=False, default=list)  # array of domain strings
    tool_capabilities = Column(JSONB, nullable=False, default=list)  # array of tool capability objects
    
    # Risk and operations
    high_risk_operations = Column(JSONB, nullable=False, default=list)
    destructive_operations = Column(JSONB, nullable=False, default=list)
    reversible_operations = Column(JSONB, nullable=False, default=list)
    
    # Inputs
    required_inputs = Column(JSONB, nullable=False, default=list)
    optional_inputs = Column(JSONB, nullable=False, default=list)
    
    # Failure surfaces
    ambiguity_points = Column(JSONB, nullable=False, default=list)
    failure_surfaces = Column(JSONB, nullable=False, default=list)
    security_surfaces = Column(JSONB, nullable=False, default=list)
    
    # Constraints
    assumptions = Column(JSONB, nullable=False, default=list)
    constraints = Column(JSONB, nullable=False, default=list)
    
    # Quality metadata
    confidence = Column(JSONB, nullable=False, default=dict)  # per-dimension confidence scores
    
    # Generation metadata
    model_used = Column(String(100), nullable=False)
    generator_version = Column(String(50), nullable=False)
    generation_timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    
    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    agent = relationship("Agent", backref="capability_profiles")
    version = relationship("AgentVersion", backref="capability_profiles")
    
    # Constraints
    __table_args__ = (
        UniqueConstraint("agent_id", "version_id", name="uq_capability_agent_version"),
    )

    def __repr__(self) -> str:
        return f"<AgentCapabilityProfile(id={self.id}, agent_id={self.agent_id}, primary_goal='{self.primary_goal[:50] if self.primary_goal else None}...')>"
